plugins:
  pfaffmanager_enabled:
    default: true
    client: true
  pfaffmanager_skip_actions:
    default: true
    client: false
    type: boolean
    default: true
  pfaffmanager_inventory_dir:
    default: /data/pfaffmanager/inventories
    client: false
    hidden: false
  pfaffmanager_vault_file:
    default: /data/pfaffmanager/vault-password.txt
    client: false
    hidden: false    
  pfaffmanager_playbook_dir:
    default: /home/pfaffman/src/literatecomputing/lc-manager-playbook
    client: false
    hidden: false        
  pfaffmanager_upgrade_playbook:
    default: /bin/true
    client: false
    hidden: false            
  pfaffmanager_do_install:
    default: /bin/true
    client: false
    hidden: false            
  pfaffmanager_api_key:
    default: ""
    client: false
    hidden: false
  pfaffmanager_do_api_key:
    default: ""
    client: false
    hidden: false
  pfaffmanager_mg_api_key:
    default: ""
    client: false
    hidden: false
  pfaffmanager_create_server_group:
    default: "CreateServer"
    client: false
    hidden: false
    type: group
  pfaffmanager_pro_server_group:
    default: "ProServer"
    client: false
    hidden: false
    type: group
  pfaffmanager_ec2_server_group:
    default: "Ec2Server"
    client: false
    hidden: false
    type: group
  pfaffmanager_ec2_pro_server_group:
    default: "EC2ProServer"
    client: false
    hidden: false
    type: group
  pfaffmanager_hosted_server_group:
    default: "LCProServer"
    client: false
    hidden: false
    type: group
  pfaffmanager_unlimited_server_group:
    default: "UnlimitedServers"
    client: false
    hidden: false
    type: group
  pfaffmanager_server_manager_group:
    default: "ServerManager"
    client: false
    hidden: false
    type: group
  pfaffmanager_debug_to_log:
    default: false
    client: false
    hidden: false
    type: boolean
    